apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
  namespace: {{ .Values.namespace }}
  labels:
    app: catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
        - name: catalog
          image: "{{ .Values.catalog.image }}:{{ .Values.catalog.tag }}"
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: RETAIL_CATALOG_PERSISTENCE_PROVIDER
              value: "in-memory"
          resources:
            requests:
              cpu: "{{ .Values.catalog.resources.requests.cpu }}"
              memory: "{{ .Values.catalog.resources.requests.memory }}"
            limits:
              cpu: "{{ .Values.catalog.resources.limits.cpu }}"
              memory: "{{ .Values.catalog.resources.limits.memory }}"
          readinessProbe:
            httpGet:
              path: /catalog/size
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /catalog/size
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
